docs/example/input/block-label.vue
docs/example/input/clearable.vue
docs/example/input/default.vue
docs/example/input/inline-label.vue
docs/example/input/password.vue
docs/example/input/size.vue
docs/example/input/unwriteable.vue
docs/zh-cn/components/input.mdx
packages/Input/__tests__/__snapshots__/index.spec.js.snap
packages/Input/__tests__/index.spec.js
packages/Input/clearable-icon.jsx
packages/Input/clearable-icon.less
packages/Input/icon-content.jsx
packages/Input/icon-content.less
packages/Input/index.jsx
packages/Input/input-block-label.jsx
packages/Input/input-label.jsx
packages/Input/input-label.less
packages/Input/input.less
packages/Input/password-icon.jsx
packages/Tab/__tests__/__snapshots__/index.spec.js.snap
src/router/index.js

feature(input):add component

---

docs/example/modal/default.vue
docs/example/modal/direct.vue
packages/Modal/__tests__/__snapshots__/index.spec.js.snap
packages/Modal/__tests__/index.spec.js
packages/Modal/modal.jsx
packages/Modal/modal.less
packages/Modal/modal.wrapper.jsx
packages/Modal/modal.wrapper.less
packages/Tab/index.jsx
packages/Tabs/index.jsx

fix(modal):fix modal animation 

---

docs/example/image/default.vue
docs/example/image/skeleton.vue
docs/zh-cn/components/image.mdx
packages/Image/__tests__/__snapshots__/index.spec.js.snap
packages/Image/__tests__/index.spec.js
packages/Image/image-skeleton.jsx
packages/Image/image-skeleton.less
packages/Image/image.less
packages/Image/index.jsx
packages/index.js
scripts/build.js
src/router/index.js

feature(image):add component

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/2-feature-request.md
.github/ISSUE_TEMPLATE/3-style.md
.github/ISSUE_TEMPLATE/4-docs.md
.github/PULL_REQUEST_TEMPLATE.md
docs/example/pagination/custom.vue
docs/example/pagination/default.vue
docs/example/pagination/limit.vue
docs/example/pagination/simple.vue
docs/example/pagination/size.vue
docs/zh-cn/components/pagination.mdx
package.json
packages/Pagination/__tests__/__snapshots__/index.spec.js.snap
packages/Pagination/__tests__/index.spec.js
packages/Pagination/_pagination-pages.jsx
packages/Pagination/index.jsx
packages/Pagination/pagination-ellipsis.jsx
packages/Pagination/pagination-item.jsx
packages/Pagination/pagination-next.jsx
packages/Pagination/pagination-pages.jsx
packages/Pagination/pagination-previous.jsx
packages/Pagination/pagination-simple.jsx
packages/Pagination/pagination.less
packages/utils/theme/color.js
packages/utils/theme/index.js
src/router/index.js

chore : add github  tempalte

---

docs/example/checkbox/size.vue
packages/Pagination/pagination.less

fix: checkbox docs and pagination custom style

---

README.md
_page/ActiveCate/index.jsx
_page/CodeShow/code.preview.less
_page/Layout/layout.common.less
_page/SiderBar/sidebar.item.less

chore: lower codePreview copyIcon z-index and change readme.md style

---

packages/Tag/__tests__/__snapshots__/index.spec.js.snap
packages/Tag/__tests__/index.spec.js
packages/Tag/index.jsx
packages/Tag/tag.less
packages/index.js

feat(tag): complete Tag component and add unit test

---

docs/example/tag/default.vue
docs/example/tag/invert.vue
docs/example/tag/type.vue
docs/zh-cn/components/tag.mdx
packages/Tag/__tests__/__snapshots__/index.spec.js.snap
packages/Tag/__tests__/index.spec.js
src/router/index.js

docs(tag): add tag docs

---

.codecov.yml
.travis.yml

ci(travis): use travis ci

---

.codecov.yml
.travis.yml
README.md
package-lock.json
package.json

ci:add test coverage 

---

.travis.yml
README.md
package-lock.json
package.json

ci(codecov): add codecov

---

docs/example/select/default.vue
docs/example/select/multiple.vue
docs/zh-cn/components/select.mdx
packages/Select/__tests__/__snapshots__/index.spec.js.snap
packages/Select/__tests__/index.spec.js
packages/Select/index.jsx
packages/Select/select-dropdown.jsx
packages/Select/select-multiple.jsx
packages/Select/select.less

fix:fix select component mutual 

---

.codecov.yml
packages/Pagination/pagination.less

chore(pagination): style change

---

README.md
babel.config.js
docs/zh-cn/quickStart/install.mdx
docs/zh-cn/quickStart/into.mdx
package-lock.json
package.json
packages/Avatar/avatar.less
packages/index.js
scripts/collect.js
scripts/rollup.config.js
src/components.js
src/main.js
src/router/index.js

build: add rollup & perf scripts func

---

_page/CodeShow/code.preview.jsx
_page/SiderBar/tabbar.mobile.jsx
_page/SiderBar/widgets.jsx
docs/example/colors/default.vue
docs/example/colors/error.vue
docs/example/colors/light.vue
docs/example/colors/success.vue
docs/example/colors/warning.vue
docs/example/icons/color.vue
docs/example/icons/component/icons-cell.vue
docs/example/icons/component/icons.vue
docs/example/icons/default.vue
docs/example/icons/size.vue
package-lock.json
package.json

build(icons): update @fect-ui/vue-icons  version dependent

---

_page/SiderBar/widgets.jsx
packages/Link/__tests__/__snapshots__/index.sepc.js.snap
packages/Link/index.tsx

---
change docs class style 
---

fix(link): fix link component props error

---

docs/example/image/invert.vue
docs/example/image/usebrowser.vue
docs/zh-cn/components/image.mdx
packages/Image/__tests__/__snapshots__/index.spec.ts.snap
packages/Image/__tests__/index.spec.ts
packages/Image/image-browser-icon.tsx
packages/Image/image-browser.tsx
packages/Image/image.less
packages/Image/index.tsx
packages/Image/type.ts
vetur/attributes.json
vetur/tags.json

feature(image): support browser style

---

.travis.yml
docs/example/skeleton/animate.vue
docs/example/skeleton/default.vue
docs/example/skeleton/loading.vue
docs/example/skeleton/more.vue
docs/example/skeleton/user.vue
docs/zh-cn/components/skeleton.mdx
packages/Select/index.tsx
packages/Skeleton/__tests__/__snapshots__/index.spec.js.snap
packages/Skeleton/__tests__/index.spec.js
packages/Skeleton/index.tsx
packages/SkeletonItem/image-skeleton.tsx
packages/SkeletonItem/index.tsx
packages/SkeletonItem/skeletonItem.less
packages/SkeletonItem/type.ts
packages/index.ts
vetur/attributes.json
vetur/tags.json

feature(skeleton):add component

---

docs/example/icons/component/icons.vue
docs/zh-cn/themes/icons.mdx
package-lock.json
package.json

docs(icons): support search and update icons version

---

docs/example/button/loading.vue
docs/example/loading/load.vue
docs/zh-cn/components/button.md
docs/zh-cn/components/loading.md
package-lock.json
package.json
packages/button/__tests__/__snapshots__/index.spec.js.snap
packages/button/__tests__/index.spec.js
packages/button/button-loading.tsx
packages/button/index.tsx
packages/image/image-browser.tsx
packages/loading/__tests__/__snapshots__/index.spec.js.snap
packages/loading/__tests__/index.spec.js
packages/loading/index.less
packages/loading/index.tsx
packages/utils/theme/propTypes.ts
vetur/attributes.json
vetur/tags.json

feature:(loading) : support loadType

---

docs/zh-cn/quickStart/install.md
docs/zh-cn/quickStart/into.md

docs(update): update version

---

package.json
packages/utils/create/index.ts

fix(component): fix error name cause install error

---

README.md

<docs>: edit the import path of main.css

---

docs/example/tabs/disabled.vue
docs/zh-cn/components/tabs.md
packages/tabs/index.tsx
vetur/attributes.json
vetur/tags.json

---
In the past version , props disabled may be cause recursive error , In this version we update the Vue version to resolve the question . And the function is restored
---

feat(tab): support props disabled

---

packages/badge-anchor/__tests__/__snapshots__/index.spec.js.snap
packages/badge-anchor/index.less
packages/badge-anchor/index.tsx
packages/breadcrumbs-item/__tests__/__snapshots__/index.spec.js.snap
packages/breadcrumbs-item/__tests__/index.spec.js
packages/breadcrumbs-item/breadcrumbs-spearator.tsx
packages/breadcrumbs-item/index.less
packages/breadcrumbs-item/index.tsx
packages/breadcrumbs/__tests__/__snapshots__/index.spec.js.snap
packages/breadcrumbs/__tests__/index.spec.js
packages/breadcrumbs/index.less
packages/breadcrumbs/index.tsx
packages/capacity/index.less
packages/dot/__tests__/__snapshots__/index.spec.js.snap
packages/dot/__tests__/index.spec.js
packages/dot/index.less
packages/dot/index.tsx
packages/tab/__tests__/__snapshots__/index.spec.js.snap
packages/tab/__tests__/index.spec.js
packages/tab/index.less
packages/tab/index.tsx
packages/tabs/index.less
packages/tabs/index.tsx
packages/tabs/tabs-title.tsx

style:(name) use bem rule replace some components

---

docs/example/Grid/auto.vue
docs/example/Grid/default.vue
docs/example/Grid/fluid.vue
docs/example/Grid/hidden.vue
docs/example/Grid/responsive.vue
docs/zh-cn/components/grid.md
docs/zh-cn/index.ts
packages/grid/__tests__/__snapshots__/index.spec.js.snap
packages/grid/__tests__/index.spec.js
packages/grid/index.less
packages/grid/index.tsx
packages/grid/props.ts
packages/grid/type.ts
packages/index.ts
page/Attributes/index.vue
vetur/attributes.json
vetur/tags.json

feature(grid) : add new component

---

docs/example/switch/default.vue
docs/example/switch/disabled.vue
docs/example/switch/size.vue
docs/zh-cn/components/switch.md
packages/modal/__tests__/index.sepc.js
packages/pagination/__tests__/index.spec.js
packages/skeleton/__tests__/index.spec.js
packages/snippet/__tests__/__snapshots__/index.spec.js.snap
packages/snippet/__tests__/index.spec.js
packages/switch/__tests__/__snapshots__/index.spec.js.snap
packages/switch/__tests__/index.spec.js
packages/switch/index.less
packages/switch/index.tsx
packages/utils/base.ts
packages/utils/format/string.ts
vetur/attributes.json
vetur/tags.json

refacotr(switch) : perf style and add new feature

---

docs/example/pagination/custom.vue
packages/loading/__tests__/__snapshots__/index.spec.js.snap
packages/loading/index.less
packages/loading/index.tsx

fix(loading): fix loading style error and docs

---

packages/breadcrumbs-item/__tests__/__snapshots__/index.spec.js.snap
packages/breadcrumbs-item/__tests__/index.spec.js
packages/capacity/__tests__/__snapshots__/index.spec.js.snap
packages/capacity/__tests__/index.spec.js
packages/col/__tests__/__snapshots__/index.spec.ts.snap
packages/col/__tests__/__snapshots__/index.spec.tsx.snap
packages/col/__tests__/index.spec.tsx
packages/progress/__tests__/index.spec.js
packages/row/__tests__/index.spec.ts
packages/spacer/__tests__/__snapshots__/index.spec.tsx.snap
packages/spacer/__tests__/index.spec.tsx
packages/switch/__tests__/index.spec.js

test(unit): improve unit testing of some components

---

docs/example/tabs/divider.vue
packages/tab/index.tsx
packages/tabs/index.tsx

perf(tabs): useState replace ref

---

docs/example/collapse/accordion.vue
docs/zh-cn/components/collapse.md
packages/collapse-group/index.less
packages/collapse-group/index.tsx
packages/collapse/__tests__/__snapshots__/index.spec.ts.snap
packages/collapse/__tests__/index.spec.ts
packages/collapse/index.tsx
packages/index.ts
vetur/attributes.json
vetur/tags.json

feature(CollaspeGroup) : add container of collapse

---

packages/modal/__tests__/__snapshots__/index.spec.ts.snap
packages/modal/__tests__/index.spec.ts
packages/modal/modal.tsx
packages/modal/type.ts
vetur/attributes.json
vetur/tags.json

fix(modal): when load modal component the Page will be lock

---

docs/example/button/icon.vue
docs/example/button/loading.vue
docs/example/rating/custom.vue
docs/example/rating/type.vue
docs/zh-cn/components/skeleton.md
packages/button/__tests__/__snapshots__/index.spec.tsx.snap
packages/button/__tests__/index.spec.tsx
packages/button/button-icon.tsx

---
---
Fix component Button icon render error

fix(button): fix can not render icon and docs error

---

docs/example/drawer/default.vue
docs/example/drawer/placement.vue
docs/zh-cn/components/drawer.md
docs/zh-cn/index.ts
packages/drawer/__tests__/__snapshots__/index.spec.ts.snap
packages/drawer/__tests__/index.spec.ts
packages/drawer/drawer-wrapper.tsx
packages/drawer/index.less
packages/drawer/index.tsx
packages/drawer/props.ts
packages/drawer/style.ts
packages/index.ts
packages/teleport/index.less
vetur/attributes.json
vetur/tags.json

feature(drawer) : add a new component 

---

CHANGELOG.md
package-lock.json
package.json

chore(changelog): update changelog and pkg version

---

packages/drawer/__tests__/__snapshots__/index.spec.ts.snap
packages/drawer/drawer-wrapper.tsx
packages/drawer/index.less
packages/drawer/index.tsx
packages/drawer/style.ts
packages/index.ts
packages/modal/modal-wrapper.tsx
packages/teleport/index.tsx
packages/utils/styles/index.css
scripts/collect.js

perf(drawer) : Optimize drawer animation

---

build/bundler.d.ts
build/bundler.js
build/index.js

perf(build): change code style remove func setEnv & cleanBuild  in index.js

---

package-lock.json
packages/breadcrumbs/__tests__/__snapshots__/index.spec.js.snap
packages/breadcrumbs/__tests__/__snapshots__/index.spec.ts.snap
packages/breadcrumbs/__tests__/index.spec.ts

test(breadcrumbs): update breadcrumbs unit test case with ts

---

packages/select-option/index.tsx
packages/select/__tests__/__snapshots__/index.spec.js.snap
packages/select/index.less
packages/select/index.tsx
packages/select/props.ts
packages/select/select-dropdown.tsx
packages/select/type.ts

fix(select): fix page scroll the element Misalignment

---

packages/modal/index.less

---
---
fix modal action style error

fix(modal): fix modal action style button loose border

---

build/bundler.js
build/constant.d.ts
build/constant.js

build(bundler): change genDTS execution order 

---

package-lock.json
package.json
packages/collapse/__tests__/index.spec.ts
packages/tooltip/__tests__/__snapshots__/test.spec.tsx.snap
packages/tooltip/__tests__/test.spec.tsx

test(packages): update tooltip & collapse coverage

---

package-lock.json
package.json

chore(theme): upgrade theme dep version

---

docs/example/tooltip/default.vue
packages/index.ts
packages/popover/__tests__/__snapshots__/index.spec.tsx.snap
packages/popover/__tests__/index.spec.tsx
packages/popover/index.less
packages/popover/index.ts
packages/popover/popover.tsx
packages/popover/props.ts
packages/tooltip/__tests__/__snapshots__/index.spec.ts.snap
packages/tooltip/__tests__/__snapshots__/test.spec.tsx.snap
packages/tooltip/index.ts
packages/tooltip/tooltip.tsx
packages/tooltip/type.ts

feat(popover): add a new component

---

packages/button/index.less
packages/button/style.ts
packages/tooltip/index.less
packages/utils/theme/propTypes.ts

feat(style): button and tooltip support more style type

---

packages/row/index.less

fix(row): fix row style can't work

---

docs/example/back-top/custom.vue
docs/example/back-top/default.vue
packages/back-top/__tests__/__snapshots__/index.spec.ts.snap
packages/back-top/__tests__/index.spec.ts
packages/back-top/back-top.tsx
packages/back-top/index.less

---
---
This pr may cause reduce test coverage .  Will fix then after uprgade jest and js-dom version .

perf(backTop) : perf and clean code 

---

build/bundler.js
build/collect.js
build/config/webpack.umd.js
build/index.js
package.json
packages/index.ts
vue.config.js

chore(build) : improve build speed

---

docs/example/tooltip/default.vue
docs/example/tooltip/trigger.vue
docs/example/tooltip/variable.vue
docs/zh-cn/components/tooltip.md
packages/tooltip/__tests__/index.spec.ts
packages/tooltip/index.less
packages/tooltip/tooltip.tsx

fix(tooltip) : fix MouseEvent can't work correctly

---

packages/md-loader/index.js

---
fix syntax:
- mardownWrapper  to markdownWrapper
- markdwonParser to markdownParser
---

fix(md-plugin): typo and change logic

---

.github/CONTRIBUTING.md
.github/CONTRIBUTING.zh-CN.md
packages/website/src/App.vue
packages/website/src/components/nav-bar/index.vue

---
---
- remove native router in `website/nav-bar`
- translate `CONTRIBUTING.md`

remove native router in website/nav-bar

---

packages/website/src/components/playground/preview.vue

---
- add playground operations tooltip
---

feat(website): add playground operations tooltip

---

packages/cli/src/commands/lint.ts

- correct misspellings of prettier's description
---

fix(cli): correct misspellings of prettier's description

---

.github/workflows/deploy-rc-website.yaml
packages/vue/components/input/__tests__/__snapshots__/index.spec.ts.snap
packages/vue/components/input/__tests__/index.spec.ts
packages/vue/components/input/input.tsx
packages/website/docs/en-us/components/input.md
packages/website/docs/example/icons/component/icons.vue
packages/website/docs/example/input/icon.vue
packages/website/docs/zh-cn/components/input.md

---
---
- Support `icon` with slot for the Input component
``` html
<fe-input placeholder="请输入关键字">
<template #icon> <Search /> </template>
</fe-input>
```

feat(input): add icon support by slot

---

packages/website/docs/en-us/guide/introduction.md
packages/website/docs/en-us/guide/quickStart.md
packages/website/docs/zh-cn/guide/introduction.md
packages/website/docs/zh-cn/guide/quickStart.md

- modify the punctuation of en/zh docs
---

fix(docs): modify the punctuation of en/zh docs

---

packages/vue/components/index.ts
packages/vue/components/theme-provide/__tests__/index.spec.ts
packages/vue/components/theme-provide/index.ts
packages/vue/components/theme-provide/interface.ts
packages/vue/components/theme-provide/theme-provide.tsx
packages/vue/components/utils/format/string.ts
packages/website/docs/en-us/components/themeprovide.md
packages/website/docs/en-us/index.ts
packages/website/docs/example/theme-provide/default.vue
packages/website/docs/zh-cn/components/themeprovide.md
packages/website/docs/zh-cn/index.ts

feat(theme-provide): add new component support custom css variable.

---

packages/vue/components/checkbox-group/__tests__/__snapshots__/index.spec.ts.snap
packages/vue/components/checkbox-group/__tests__/index.spec.tsx
packages/vue/components/checkbox/checkbox.tsx
packages/vue/components/checkbox/index.less
packages/vue/components/radio-group/__tests__/__snapshots__/index.spec.ts.snap
packages/vue/components/radio/index.less
packages/vue/components/radio/radio.tsx
packages/vue/components/switch/__tests__/__snapshots__/index.spec.ts.snap
packages/vue/components/switch/index.less
packages/vue/components/switch/switch.tsx
packages/vue/components/utils/create/create-bem.ts
packages/vue/components/utils/create/index.ts

feat: Radio & Switch & Checkbox support css vars

---

packages/vue/components/button-group/__tests__/__snapshots__/index.spec.tsx.snap
packages/vue/components/button-group/__tests__/index.spec.tsx
packages/vue/components/button-group/button-group-context.ts
packages/vue/components/button-group/button-group.tsx
packages/vue/components/button-group/index.less
packages/vue/components/button-group/index.ts
packages/vue/components/button-group/interface.ts
packages/vue/components/button-group/props.ts
packages/vue/components/button/button.tsx
packages/vue/components/button/index.less
packages/vue/components/index.ts
packages/website/docs/en-us/components/button.md
packages/website/docs/example/button/group.vue
packages/website/docs/zh-cn/components/button.md

feat(button-group): add new component

---

packages/vue/components/tab/index.less
packages/vue/components/tab/tab.tsx
packages/vue/components/tabs/__tests__/__snapshots__/index.spec.tsx.snap
packages/vue/components/tabs/__tests__/index.spec.tsx
packages/vue/components/tabs/index.less
packages/vue/components/tabs/interface.ts
packages/vue/components/tabs/props.ts
packages/vue/components/tabs/style.ts
packages/vue/components/tabs/tabs-highlight.tsx
packages/vue/components/tabs/tabs-title.tsx
packages/vue/components/tabs/tabs.tsx
packages/website/docs/en-us/components/tabs.md
packages/website/docs/example/tabs/default.vue
packages/website/docs/zh-cn/components/tabs.md

[Feature:tabs]: support hover block & perf style

---

packages/vue/components/button/__tests__/index.spec.tsx
packages/vue/components/index.ts
packages/vue/components/upload/__tests__/index.spec.tsx
packages/vue/components/upload/index.less
packages/vue/components/upload/index.ts
packages/vue/components/upload/interface.ts
packages/vue/components/upload/props.ts
packages/vue/components/upload/upload.tsx
packages/vue/components/utils/format/object.ts
packages/website/docs/en-us/components/upload.md
packages/website/docs/en-us/index.ts
packages/website/docs/example/upload/default.vue
packages/website/docs/zh-cn/components/upload.md
packages/website/docs/zh-cn/index.ts

[Feature]: add new component upload

---

packages/vue/components/select-option/index.less
packages/vue/components/select-option/select-option.tsx
packages/vue/components/select/interface.ts
packages/vue/components/select/props.ts
packages/vue/components/select/select.tsx
packages/website/docs/example/select/size.vue

[Feature]: select component redesgin checked.

---

packages/vue/components/radio/radio.tsx

---
---
Remove incorrect initialization check

fix: radio initial value

---

packages/vue/components/input/index.less

fix(input): ignore edge password default style

---

packages/vue/src/drawer/__tests__/__snapshots__/index.spec.ts.snap
packages/vue/src/drawer/drawer.tsx
packages/vue/src/drawer/props.ts
packages/vue/src/modal/__tests__/__snapshots__/index.spec.ts.snap
packages/vue/src/modal/function-call.tsx
packages/vue/src/modal/index.less
packages/vue/src/modal/modal.tsx
packages/vue/src/modal/props.ts
packages/vue/src/teleport/index.less
packages/vue/src/teleport/teleport.tsx
packages/vue/src/tooltip/__tests__/__snapshots__/index.spec.ts.snap
packages/vue/src/tooltip/__tests__/__snapshots__/test.spec.tsx.snap
packages/website/docs/en-us/components/drawer.md
packages/website/docs/en-us/components/modal.md
packages/website/docs/zh-cn/components/drawer.md
packages/website/docs/zh-cn/components/modal.md

---
---
Support using the esc key to close the popup

[Feature]: Modal & Drawer support keyboard

---

packages/vue/src/avatar-group/__tests__/__snapshots__/index.spec.tsx.snap
packages/vue/src/button/button.tsx
packages/vue/src/checkbox/checkbox.tsx
packages/vue/src/radio-group/__tests__/__snapshots__/index.spec.ts.snap
packages/vue/src/radio-group/radio-group.tsx
packages/vue/src/radio/index.less
packages/vue/src/radio/radio.tsx
packages/vue/src/utils/create/pick-context.ts

[FIX]: fix pickContextProps logic 

---

packages/vue-hooks/package.json
packages/vue-hooks/src/use-click-away/use-click-away.ts
packages/vue/src/breadcrumbs-item/breadcrumbs-item.tsx
packages/vue/src/breadcrumbs/breadcrumbs.tsx
packages/vue/src/breadcrumbs/interface.ts
packages/vue/src/select-option/select-option.tsx
packages/vue/src/select/interface.ts
packages/vue/src/select/select.tsx
packages/vue/src/skeleton-item/skeleton-item.tsx
packages/vue/src/skeleton/interface.ts
packages/vue/src/skeleton/skeleton.tsx
packages/vue/src/tooltip/tooltip.tsx
packages/website/docs/example/skeleton/animate.vue
packages/website/docs/example/skeleton/default.vue

[Fix] component not responsive

---

packages/vue/src/textarea/__tests__/index.spec.ts
packages/vue/src/textarea/auto-height.ts
packages/vue/src/textarea/index.less
packages/vue/src/textarea/textarea.tsx
packages/vue/src/utils/composables/use-portal.ts
packages/vue/src/utils/format/number.ts
packages/website/docs/en-us/index.ts

---
---
Fix it. and add en-us docs root entry

[Fix]: textarea component auto heigh can't scale

---

packages/vue/src/form-item/form-item.tsx
packages/vue/src/form-item/index.less
packages/vue/src/form/__tests__/__snapshots__/index.spec.ts.snap
packages/vue/src/form/interface.ts
packages/website/docs/en-us/components/form.md
packages/website/docs/en-us/components/tabs.md
packages/website/docs/zh-cn/components/form.md
packages/website/docs/zh-cn/components/tabs.md

---
---
Added animation effect to error log

[Style]: perf form errlog style

---

packages/vue/jest.config.js
packages/vue/src/affix/affix.tsx
packages/vue/src/affix/index.less
packages/vue/src/affix/index.ts
packages/vue/src/affix/interface.ts
packages/vue/src/affix/props.ts
packages/vue/src/index.ts
packages/vue/src/utils/format/dom.ts
packages/vue/src/utils/format/number.ts
packages/vue/src/utils/format/unit.ts
packages/website/docs/en-us/components/affix.md
packages/website/docs/en-us/index.ts
packages/website/docs/example/affix/default.vue
packages/website/docs/example/affix/position.vue
packages/website/docs/zh-cn/components/affix.md
packages/website/docs/zh-cn/index.ts

[Feat]: add new component Affix

---

packages/vue/src/tag/__tests__/index.spec.ts
packages/vue/src/tag/index.less
packages/vue/src/tag/tag.tsx
packages/website/docs/en-us/components/tag.md
packages/website/docs/example/tag/color.vue
packages/website/docs/example/tag/round.vue
packages/website/docs/zh-cn/components/tag.md

---
---
add color and round attribute to tag component

feat(tag): add color and round attribute

---

packages/vue/src/input/__tests__/index.spec.ts
packages/vue/src/input/input.tsx

---
---
- Fix prop `type` can't update dynamic.
- Fix prop `type` as `number` cause err.

fix(input): htmlType as number cause err

---

packages/vue/src/switch/__tests__/index.spec.ts
packages/vue/src/switch/switch.tsx

fix(switch): switch cannot watch the change of value

---

packages/vue/src/loading/loading.tsx
packages/vue/src/pagination/pagination-pages.tsx
packages/vue/src/rating/rating.tsx
packages/vue/src/spinner/spinner.tsx
packages/vue/src/swipe/swipe.tsx
packages/vue/src/utils/format/arrary.ts

---
---
For more performance. I decide add a make func. You can see it's very clean.

feat(utils): add make func & clean code

---

Makefile

Test netlify deploy-preview
---
---
related issue: https://github.com/fect-org/fect/issues/208

style: remove extra spaces

---

package.json
packages/vue-hooks/babel.config.js
packages/vue-hooks/build.ts
packages/vue-hooks/non.config.ts
packages/vue-hooks/package.json
packages/vue-icons/README.md
packages/vue-icons/babel.config.js
packages/vue-icons/index.ts
packages/vue-icons/package.json
packages/vue-icons/scripts/bundler.ts
yarn.lock

In past. Fect sub package is dependence `cli` bundler. But it's not fit. So this pr will change the bundler.

[Chore]: Change the bundler

---

internal/plugins/analyze.ts
package.json

---
Fix internal analyzed plugin generator err.

Fix(internal): style analyze suffix err

---

packages/vue/src/backdrop/backdrop.tsx
packages/vue/src/backdrop/index.less
packages/vue/src/drawer/__tests__/__snapshots__/index.spec.ts.snap
packages/vue/src/drawer/__tests__/index.spec.ts
packages/vue/src/drawer/drawer-wrapper.tsx
packages/vue/src/drawer/drawer.tsx
packages/vue/src/drawer/index.less
packages/vue/src/drawer/props.ts
packages/vue/src/index.ts
packages/vue/src/modal/index.less
packages/vue/src/modal/modal.tsx

[Refactor]: drawer

---

docs/layout/common/table.css
docs/layout/components/header/header.vue
docs/layout/components/home/home.vue
example/index.js
internal/index.ts
mdi/markdown.ts
mdi/table.ts
package.json
tsconfig.json
vite.config.ts
yarn.lock

Document: perf logic

---

docs/layout/common/front-matter.ts
docs/layout/common/global.ts
docs/layout/common/loader.ts
docs/layout/common/route.ts
docs/layout/components/header/mobile-menu.vue
docs/layout/components/navbar/nav-bar.vue
docs/layout/components/search/search-result.vue
docs/layout/components/search/search.vue
docs/layout/composables/use-aside.ts
docs/layout/main.ts
docs/zh-cn/components/icons.md
package.json
vite.config.ts

---
- Use dynamic load static file. (import.meta.glob) is enough. 
- Refactor storage struct.
- Split bundle chunk.

Perf: document bundle

---

example/toast/default.vue
packages/vue/src/toast/__tests__/__snapshots__/index.spec.tsx.snap
packages/vue/src/toast/__tests__/function.spec.ts
packages/vue/src/toast/__tests__/index.spec.tsx
packages/vue/src/toast/function-call.tsx
packages/vue/src/toast/index.less
packages/vue/src/toast/interface.ts
packages/vue/src/toast/props.ts
packages/vue/src/toast/toast-item.tsx
packages/vue/src/toast/toast.tsx
packages/vue/src/utils/format/object.ts
tsconfig.json

---
---
Remove props closeAble.( It's no necessary. Will use actions replace it.

feat: redesign toast component

---

docs/layout/global.d.ts
netlify.toml
package.json
plugins/vite/cdn/README.md
plugins/vite/cdn/index.ts
shims/shims-vue.d.ts
vite.config.ts
yarn.lock

[Chore]: perf document load speed
